apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
   name: anonymous-csr
spec:
   groups:
   - system:authenticated
   request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JUQ0NBVlVDQVFBd0tERVNNQkFHQTFVRUF3d0pZVzV2Ym5sdGIzVnpNUkl3RUFZRFZRUUtEQWxoYm05dQplVzF2ZFhNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURGVkg2SDVJeDVpb3IxCnNZdXJBVzJxajRrL1l4UU5FWVlIQkxtV1lwcktWSlFHeHVUK3djV3ZsdEpzcERhaTVWbS9QS1JYNzBjSW9nQSsKcFhTSmxHaGFFYzZ2aW5kN1ErVHBIWlJ1YlRjVWUyMStpTWYvN0FadEtPZTFKL1RwSklSTTB2aFdmcEVvVnAyVQpqQUVyOFpMWnFlS2RaWWVham1PRm1LVFBHVGZyZ01qOFdjWlBQZW8zbVg1b1prWklFMmZ0QUNjaktmVGN6cWpJCmF2YVRWemRwWStQQS9uOElZWnhIUXZER0F0Tllvd0FTZGp0U01WRzQ2TFVQU0FmZGREcEJpeDV4WTBsZ2Rldk8KNCtUWUh3d0VnelpQd1RPS1drdkZoK0R3YnB2R3VYenhuTDY0NDl5ZDRpUFNpaldBT0htQy83K2QwVDJlWURXOQorQUpueUpIbkFnTUJBQUdnQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWJqWk92WjNJV1NtRkVKeFhNUVN5CnFPQ1VyK1JxdmZ0QW1wQ0lxNS9VMUtITmxySHYzV1dvQkthRjBEM3VtbWJ4djhZN0FhZlphNHpVSnNBWU8zNTAKRjhWak9BWVlBTC9UcEVQbEx1c1ZWSjAxSFJKbmhMM3hKbmxhNENrNXpXYkJIVzJzUm82Z2JJMGkydncrWTJTTgpyWmJiSkQzcHRwckVISDlpbTg0c0EyYXUxTGJjRzNFUTQ5Yk9FVWh3M1JmZk5iNWZpUnhEY2N1WXVFT0llMnMwCmo4bGIxTmFiZ04xUzc1M003OERZdUVaL0F1SWFCWmpwTXZGWFViY013dTN5ckdRK0V2UThFK1NWUm9KZyt5b2QKQUJLUm5XZ00rK3FUa09KcDBQRVBiUVJhaFJXeGoxQkVkRi8xWFlpY2YyaUg0cytrSElLN3BXa3g0OWtjU0lQeQptZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
   signerName: kubernetes.io/kube-apiserver-client
   usages:
   - digital signature
   - key encipherment
   - client auth
