apiVersion: v1
data:
  log.level: DEBUG
  queues.yaml: |-
    partitions:
      - name: default
        preemption:
          enabled: true
          # Enabling quota preemption
          quotapreemptionenabled: true
        queues:
          - name: root
            submitacl: '*'
            queues:
              - name: parent
                resources:
                  max:
                    memory: 300Mi
                    vcore: 300m
                queues:
                  - name: queue-a
                    resources:
                      guaranteed:
                        memory: 100Mi
                        vcore: 100m
                      max:
                        memory: 200Mi
                        vcore: 200m
                    properties:
                      # Quota preemption in a queue requires delay to be set
                      quota.preemption.delay: 1000s
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-05T02:10:21Z"
  name: yunikorn-configs
  namespace: yunikorn
  resourceVersion: "39757"
  uid: 33f938a8-ad82-4811-89f1-940f5fed670e
