apiVersion: v1
kind: Service
metadata:
  name: yunikorn-service
  labels:
    app: yunikorn
    chart: {{ include "yunikorn.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http1
      protocol: TCP
      name: yunikorn-core
    - port: {{ .Values.service.port_web }}
      targetPort: http2
      protocol: TCP
      name: yunikorn-service
  selector:
    app: yunikorn
    release: {{ .Release.Name }}
