apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
   name: anonymous-csr
spec:
   groups:
   - system:authenticated
   request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JUQ0NBVlVDQVFBd0tERVNNQkFHQTFVRUF3d0pZVzV2Ym5sdGIzVnpNUkl3RUFZRFZRUUtEQWxoYm05dQplVzF2ZFhNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURPQnU0RW95SC9DUEZ2CmhMcUs1TlYyU0pzYnZaYjBCY0dSczhwWlVXaE1lTEZXMTNlUkszR21BN3REUUhDekRiZFdsRWNtUm9TdUdMbEkKUk9VVlJJZlIrUmZBVDZjYkJvS0hEanVDTkFDSE9ianErRHd0dzNtbUxCelVwVDlFS3NvMUxPUmlnWnh6T3NRagowZ2lhc0lWWmhHeDFSUkNLckhEdlhJdloxRFVHcmJqVHl0U2szYUs0czJoKzdPWGlnd3NwNFdNc0lZUUludCtsCkRGdWFrMGpDYWVGREhJS0pMblVjNUlBdE5naDBDMmRYazFocG40c29vb2MxRmVXclhCai92U1RhVVlxcUVZWTIKVVplUCtnNnlZaDdibHlON2ZocTljUVl2aU50R1kvN2xuMUJnaTdWd0xOS2ZTS1NTd2YvTGV6QTRkZ0kvbVFiZwpaVitmM2lCUEFnTUJBQUdnQURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWVQaExsZUtPTzNCaVZvQnQwM0VRCmxHL0RRNTNMWlJ1eUF4SzBQYTR0RVorWU40YWZTT2dpZ0lTajRGVU80eXVRaENLWTFVcGUxVjNVUTRReExudzQKZnBOaFJKZG5KaW1qVEh3bjg5bzVaN2JTUzY2ZUdYMWhYRUV4cWx6c0hSOSs2SW04L2dndWdIVWtWODgvWThZRgpqLzVVVjIwdHZNazdFMVZVeHdRTEp2eW9hWjJvWUFoRThkcTRQcnQ1NDVabU0xc29ZbTA5aVI0OHBIbkhWOFdsCnJ5aXRTOTN5SVB1b2M3aDFiWEVjMmhDR1U1SnNjRmViU0lwSGNXbjVNS2pxSmNMdy96MFhpNmllUXB2NTZ3QzkKamh3YWZhYlVOL01ab1lmSUdkNWtDSXhFR1EvZWNTalF1dDFMakhlVTIvSUpWL2dheFRxS3JkdnlQU0hFVXdZTQpFdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
   signerName: kubernetes.io/kube-apiserver-client
   usages:
   - digital signature
   - key encipherment
   - client auth
