# Claim an EBS PersistentVolume.
# Dynamic provisioning through the storageClassName
# see: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/
# kube API server must have --enable-admission-plugins DefaultStorageClass
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-claim-auto
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-with-volume
  labels:
    applicationId: "pod-with-ebs-auto"
    queue: "root.sandbox"
spec:
  schedulerName: yunikorn
  containers:
    - name: pod-with-ebs-auto
      image: alpine
      resources:
        requests:
          cpu: "100m"
          memory: "500M"
      # Mount the EBS volume in the container
      volumeMounts:
        - name: ebs-auto
          mountPath: "/var/tmp/mytest"
      # Write to a file inside our mounted path
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/tmp/mytest/dates.txt; sleep 5; done"]
  # Add the EBS volume claim
  volumes:
    - name: ebs-auto
      persistentVolumeClaim:
        claimName: ebs-claim-auto

