apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yunikorn-admission-controller
  namespace: yunikorn
  labels:
    app: yunikorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yunikorn
  template:
    metadata:
      labels:
        app: yunikorn
    spec:
      containers:
        - name: yunikorn-admission-controller-webhook
          image: yunikorn/yunikorn-scheduler-admission-controller:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8443
            name: webhook-api
          volumeMounts:
          - name: webhook-tls-certs
            mountPath: /run/secrets/tls
            readOnly: true
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: webhook-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: yunikorn-admission-controller-service
  namespace: yunikorn
  labels:
    app: yunikorn
spec:
  ports:
    - port: 443
      targetPort: webhook-api
  selector:
    app: yunikorn
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: yunikorn-admission-controller-cfg
  labels:
    app: yunikorn
webhooks:
  - name: admission-webhook.yunikorn.svc
    clientConfig:
      service:
        name: yunikorn-admission-controller-service
        namespace: yunikorn
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXlOVEl6TkRFd09Wb1hEVEk1TVRBeU1qSXpOREV3T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXFJCldKb2RnamFzV0x1QVYxUFdhekFCYURsakk5MzNJdFJLUDJJNDVEb3liYU9aUE1GdlhRRVQ5L2Fqdk9OSjkwQXAKOHN1bkRSNzlSa3V5azJ0bkRSWUtTcVowNEhNTDlBT0NUZ3VvSzUxbXAwR25oNjNxZk5DNkY3clltRkdJTWt0VApUWVZDU0lXWXI2Y3NSRm1oMkkvRWc1SWJNWFRFUFUrQ1cvdDVrZGpDbkdUTno5clhvb2pWajlmSDFjVHlmWXFLCkJtSW9ZdURtTmZzOXBhOURCWVVpN2Y2aHZQc08vT3NHTDdNdXBQVDNuN2t0dXg4ZXRhL2Z3Wms5RWZVWmlMUEgKWHhmdmlCS0xiMHZPTDkzTndNakJkMDI0b1N1Q2E4Y0w4VkJkbXdvWGVKL3JOazF2bnQvRy9OWGY5THVlRXJScgpnVGdsWENIT0Z0a2VWZ0VieTZzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDS2dRbytGbUdPOXpGU296UHV5b1lrRnVDY3cKdG9rUG94Q2JKVHFZdk16TG9hZGhUcGZQcFpnWHYweHB4d09kL2Z2SW5qVHYyU0pmenJoSDkxVWJOUktWdGdNQgpxQ1IvNWxLZjJ0UzJVamErNXFmRjdscXltUmpQNlNwWWludGdTaGs3bTc1WUdCZTZoWWtpQVhkTEpVN0QySGx2CjZoaHlZMG9qV2p2bEZITFpjSW5JdWpHL2NiQ2QwNXVlRHUxam45Z2N4dE9GVGtmZERSQ0NOUGE5K2JWd1N6Q2EKYzk1L2hKQTVGQnJRcEZYaTgvei9id1hKVnBELzFpYzluZ3ZPVmh2b29QQ0FpS0xLaUdsdmVudXV1bXBVL0t2NwpybmdwTXhGV0V1dUFjUjI5RE1ITll2QWgzSlRVelN4dGhJNENETm43VSs3SHk3VU5XR1hZdnlWQ0JEcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
