
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "username-rule-example01"
    yunikorn.apache.org/username: finance.test
  name: task0
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-30s
      image: "alpine:latest"
      command: ["sleep", "30"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "username-rule-example02"
    yunikorn.apache.org/username: developer
  name: task1
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-30s
      image: "alpine:latest"
      command: ["sleep", "30"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"

#  partitions:
#    - name: default
#      placementrules:
#        - name: user
#          create: false
#      queues:
#      - name: root
#        submitacl: '*'
#        queues:
#        - name: finance_dot_test
