
apiVersion: v
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "prvoided-rule-example01"
    queue: "my_special_queue"
    yunikorn.apache.org/username: developer
  name: task0
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-30s
      image: "alpine:latest"
      command: ["sleep", "30"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"

#  partitions:
#    - name: default
#      placementrules:
#        - name: fixed
#          value: last_resort
#      queues:
#      - name: root
#        submitacl: '*'
