apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: yunikorn
  name: yunikorn-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yunikorn
      name: yunikorn-scheduler
    spec:
      hostNetwork: true
      containers:
        - name: yunikorn-scheduler-core
          image: yunikorn/scheduler-core:0.1.11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/yunikorn/
        - name: yunikorn-scheduler-web
          image: yunikorn/scheduler-web:0.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9889
      volumes:
        - name: config-volume
          configMap:
            name: yunikorn-configs
---
apiVersion: v1
kind: Service
metadata:
  name: yunikorn-service
  labels:
    app: yunikorn-service
spec:
  ports:
    - name: yunikorn-service
      port: 9889
    - name: yunikorn-core
      port: 9080
  selector:
    app: yunikorn
  type: LoadBalancer