apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: yunikorn
  name: yunikorn-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yunikorn
        component: yunikorn-scheduler
      name: yunikorn-scheduler
    spec:
      hostNetwork: true
      containers:
        - name: yunikorn-scheduler-k8s
          image: yunikorn/yunikorn-scheduler-k8s:latest
          env:
            - name: LOG_ENCODING
              value: console
            - name: LOG_LEVEL
              value: '-1'
            - name: CLUSTER_ID
              value: myCluster
            - name: CLUSTER_VERSION
              value: latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/yunikorn/
        - name: yunikorn-scheduler-web
          image: yunikorn/yunikorn-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9889
      volumes:
        - name: config-volume
          configMap:
            name: yunikorn-configs
