apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: yunikorn
  name: yunikorn-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yunikorn
  template:
    metadata:
      labels:
        app: yunikorn
      name: yunikorn-scheduler
    spec:
      containers:
        - name: yunikorn-scheduler-k8s
          image: yunikorn/yunikorn-scheduler-k8s:0.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
        - name: yunikorn-scheduler-web
          image: yunikorn/yunikorn-web:0.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9889

---
apiVersion: v1
kind: Service
metadata:
  name: yunikorn-service
  labels:
    app: yunikorn-service
spec:
  ports:
    - name: yunikorn-service
      port: 9889
    - name: yunikorn-core
      port: 9080
  selector:
    app: yunikorn
  type: LoadBalancer