apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: yunikorn
  name: yunikorn-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yunikorn
      name: yunikorn-scheduler
    spec:
      hostNetwork: true
      containers:
        - name: yunikorn-scheduler-k8s
          image: yunikorn/yunikorn-scheduler-k8s:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/yunikorn/
        - name: yunikorn-scheduler-web
          image: yunikorn/yunikorn-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9889
      volumes:
        - name: config-volume
          configMap:
            name: yunikorn-configs
