# This yaml sets the schedulerName to "yunikorn", it also has
# the required info such as queue and applicationId defined. Even
# if the admission controller is running, we don't expect this info
# to be overwritten by the admission controller.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        applicationId: "nginx_do_not_replace_my_id"
        queue: root.default
      name: nginx
    spec:
      schedulerName: yunikorn
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          resources:
            requests:
              cpu: "500m"
              memory: "1024M"

