name: Weekly K8s intermediate versions e2e test

on:
    schedule:
      - cron: '0 0 * * 0' # Every Sunday at 00:00 UTC
    workflow_dispatch: {}

jobs:
  weekly-e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s:
          [
            v1.33.1,
            v1.32.2,
            v1.31.6,
            v1.30.10,
            v1.29.14,
            v1.28.15,
            v1.27.16,
            v1.26.15,
            v1.25.16,
            v1.24.17,
          ]
        plugin: ["", "--plugin"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go_version
      - name: Set hugepage
        run: |
          echo "vm.nr_hugepages = 1024" | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p
          sudo sysctl -a | grep vm.nr_hugepages
      - name: Cache and Restore e2e required tools
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            tools
          key: ${{ runner.os }}-e2e-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-e2e-
      - run: ./scripts/run-e2e-tests.sh -a "test" -n "yk8s" -v "kindest/node:${KIND_NODE_IMAGE}" ${KIND_EXTRA_ARGS}
        env:
          KIND_NODE_IMAGE: ${{ matrix.k8s }}
          KIND_EXTRA_ARGS: ${{ matrix.plugin }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: ${{ github.job }} stdout (${{ matrix.k8s }}${{ matrix.plugin == '--plugin' && format(', {0}', matrix.plugin) || matrix.plugin }})
          path: build/e2e
