
apiVersion: v
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "prvoided-rule-example01"
    queue: "my_special_queue"
    yunikorn.apache.org/username: developer
  name: task0
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-30s
      image: "alpine:latest"
      command: ["sleep", "30"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"
---
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "prvoided-rule-example02"
    queue: "root.my_special_queue"
    yunikorn.apache.org/username: developer
  name: task1
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-30s
      image: "alpine:latest"
      command: ["sleep", "30"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"

#  partitions:
#    - name: default
#      placementrules:
#        - name: provided
#          create: true
#          parent:
#            name: user
#            create: true
#      queues:
#      - name: root
#        submitacl: '*'
#        queues:
#        - name: my_special_queue
