{
 "title": "Yunikorn-pprof",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "go_memstats_alloc_bytes_total{job=~\"yunikorn\"}",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"yunikorn\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=~\"yunikorn\"} - go_memstats_frees_total{job=~\"yunikorn\"}",
     "legendFormat": "# of live objects"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"yunikorn\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=~\"yunikorn\"}[30s])"
    }
   ]
  }
 ]
}