{
 "title": "Yunikorn",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Queue", "query": { "query": "metrics(yunikorn.+resource$)" } }
  ]
 },
 "panels": [
  { "title": "Yunikorn scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Applications",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_scheduler_application_total",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Application Submissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "yunikorn_scheduler_application_submission_total",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Total # of containers allocation attempt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "yunikorn_scheduler_container_allocation_attempt_total",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "P95 Scheduling latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(yunikorn_scheduler_scheduling_latency_milliseconds_bucket[60s])) by (le))",
     "legendFormat": "milliseconds"
    }
   ]
  },
  {
   "title": "P95 Try Node latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(yunikorn_scheduler_trynode_latency_milliseconds_bucket[60s])) by (le))",
     "legendFormat": "milliseconds"
    }
   ]
  },
  {
   "title": "P95 Try Preemption latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(yunikorn_scheduler_trypreemption_latency_milliseconds_bucket[30s])) by (le))",
     "legendFormat": "milliseconds"
    }
   ]
  },
  {
   "title": "vcore_node_usage_total",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_scheduler_vcore_node_usage_total",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "ephemeral_storage_node_usage_total",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_scheduler_ephemeral_storage_node_usage_total",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "memory_node_usage_total",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_scheduler_memory_node_usage_total",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "pods_node_usage_total",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_scheduler_pods_node_usage_total",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "Queue",
   "collapsed": true,
   "panels": [
    {
     "title": "Application Status",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=~\"yunikorn_root_${Queue}_queue_app\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Application Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 22 },
     "targets": [
      {
       "expr": "{__name__=~\"yunikorn_root_${Queue}_queue_app\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=~\"yunikorn_root_${Queue}_queue_resource\", resource=\"pods\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "targets": [
      {
       "expr": "{__name__=~\"yunikorn_root_${Queue}_queue_resource\", resource=\"pods\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Vcore",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "{__name__=~\"yunikorn_root_${Queue}_queue_resource\", resource=\"vcore\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "{__name__=~\"yunikorn_root_${Queue}_queue_resource\", resource=\"memory\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  }
 ]
}